{
  "hash": "e3d3112ba365d0aeefd6340ac168959d",
  "result": {
    "markdown": "---\ntitle: \"Week 2 Challenge Instructions\"\nauthor: \"Yakub Rabiutheen\"\ndescription: \"Describing the Basic Structure of a Network\"\ndate: \"03/5/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\n# editor: visual\ncategories: \n  - challenge_2\n  # - railroads\n  # - faostat\n  # - wildbirds\n---\n\n::: {.cell}\n\n```{.r .cell-code}\nlibrary(readr)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'readr' was built under R version 4.1.3\n```\n:::\n\n```{.r .cell-code}\nlibrary(igraph)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning: package 'igraph' was built under R version 4.1.3\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\n\nAttaching package: 'igraph'\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following objects are masked from 'package:stats':\n\n    decompose, spectrum\n```\n:::\n\n::: {.cell-output .cell-output-stderr}\n```\nThe following object is masked from 'package:base':\n\n    union\n```\n:::\n:::\n\n\n## Challenge Overview\n\nFor my Challenges , I will be doing the Game of Thrones Likes vs Dislike Dataset.\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngot_like_dislike <- read_csv(\"_data/got/got_like_dislike.csv\")\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nRows: 46 Columns: 49\n-- Column specification --------------------------------------------------------\nDelimiter: \",\"\nchr  (3): Current house, Former house, Name\ndbl (46): Lysa Arryn, Petyr Baelish, Joffrey Baratheon, Margaery Tyrell, Ren...\n\ni Use `spec()` to retrieve the full column specification for this data.\ni Specify the column types or set `show_col_types = FALSE` to quiet this message.\n```\n:::\n:::\n\n1. List and inspect List the objects to make sure the datafiles are working properly.\n\nBelow are the list of Objects in the Game of Thrones Like_Dislike Dataset\n\n::: {.cell}\n\n:::\n\n\n\n2.Network Size What is the size of the network? You may use vcount and ecount.\n\nFirst I will transform this into an igraph object\n\n\n::: {.cell}\n\n```{.r .cell-code}\ngot_like_dislike.ig <- graph_from_data_frame(got_like_dislike)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in graph_from_data_frame(got_like_dislike): In `d' `NA' elements were\nreplaced with string \"NA\"\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nvcount(got_like_dislike.ig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 11\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\necount(got_like_dislike.ig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 46\n```\n:::\n:::\n\n\n\n\nThis Network has 11 vertices and 46 edges.\n\n3.Network features Are these networks weighted, directed, and bipartite?\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nis.bipartite(got_like_dislike.ig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nis.directed(got_like_dislike.ig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] TRUE\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\nis.weighted(got_like_dislike.ig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] FALSE\n```\n:::\n:::\n\n\nThis Network is a Directed, NonWeigthed and NonBipartite netowrk.\n\n\n4.Network Attributes Now, using commands from either statnet or igraph, list the vertex and edge attributes.\n\nBelow are the Network Attributes\n\n::: {.cell}\n\n```{.r .cell-code}\nigraph::vertex_attr_names(got_like_dislike.ig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] \"name\"\n```\n:::\n:::\n\nHere are the Names of Characters being used in Dislike vs Like\n\n::: {.cell}\n\n```{.r .cell-code}\nigraph::edge_attr_names(got_like_dislike.ig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n [1] \"Name\"                  \"Lysa Arryn\"            \"Petyr Baelish\"        \n [4] \"Joffrey Baratheon\"     \"Margaery Tyrell\"       \"Renly Baratheon\"      \n [7] \"Robert Baratheon\"      \"Stannis Baratheon\"     \"Brienne of Tarth\"     \n[10] \"Bronn\"                 \"Gregor Clegane\"        \"Sandor Clegane\"       \n[13] \"Xaro Xhoan Daxos\"      \"Gendry\"                \"Balon Greyjoy\"        \n[16] \"Theon Greyjoy\"         \"Jaqen H'ghar\"          \"Hodor\"                \n[19] \"Khal Drogo\"            \"Cersei Lannister\"      \"Jaime Lannister\"      \n[22] \"Lancel Lannister\"      \"Tyrion Lannister\"      \"Tywin Lannister\"      \n[25] \"Maester Luwin\"         \"Melisandre\"            \"Jeor Mormont\"         \n[28] \"Jorah Mormont\"         \"Osha\"                  \"Podrick Payne\"        \n[31] \"Pyat Pree\"             \"Grand Maester Pycelle\" \"Ros\"                  \n[34] \"Davos Seaworth\"        \"Shae\"                  \"Jon Snow\"             \n[37] \"Arya Stark\"            \"Bran Stark\"            \"Catelyn Stark\"        \n[40] \"Robb Stark\"            \"Sansa Stark\"           \"Daenerys Targaryen\"   \n[43] \"Viserys Targaryen\"     \"Samwell Tarly\"         \"Loras Tyrell\"         \n[46] \"Varys\"                 \"Eddard Stark\"         \n```\n:::\n:::\n\n\nDyad Census\n\n::: {.cell}\n\n```{.r .cell-code}\nigraph::dyad.census(got_like_dislike.ig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n$mut\n[1] 1\n\n$asym\n[1] 12\n\n$null\n[1] 42\n```\n:::\n:::\n\nIt's interesting that  lot of Null values, which means there are Characters that no one Likes or Dislikes. Which would make sense as some characters such as Khal Dago don't have any interaction with most GOT characters.\n\nTranstivity\n\n::: {.cell}\n\n```{.r .cell-code}\ntransitivity(got_like_dislike.ig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2368421\n```\n:::\n:::\n\n::: {.cell}\n\n```{.r .cell-code}\ntransitivity(got_like_dislike.ig, type = 'global')\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2368421\n```\n:::\n:::\n\n\nA Global Transitvity of 0.2368 indicates that there are some local clusters or communities in the network, but they are not highly interconnected or cohesive.\n\n\n\n\n\n\n::: {.cell}\n\n```{.r .cell-code}\ntransitivity(got_like_dislike.ig, type = 'average') \n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5867347\n```\n:::\n:::\n\nThe  average transitivity value of 0.5867347 suggests that there may be certain nodes or subgroups of nodes in the network that have a much higher level of clustering or tendency to form triangle.\n\nNow  I will look at Path Length , Number of Components and number of nodes in each connected component of the network.\n\n\n::: {.cell}\n\n```{.r .cell-code}\naverage.path.length(got_like_dislike.ig,directed = T)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1.3\n```\n:::\n\n```{.r .cell-code}\nigraph::components(got_like_dislike.ig)$no\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 1\n```\n:::\n\n```{.r .cell-code}\nigraph::components(got_like_dislike.ig)$csize\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 11\n```\n:::\n:::\n\n1.The average path length of 1.3 indicates  relatively small and tightly interconnected network.\n2. The value of 1 indicates that there is only one connected component in the network, which means that all nodes in the network are connected to each other by paths.\n3.There are 11 nodes in the largest connected component of the network. This indicates that the network is highly connected, and there are no isolated nodes or subgroups of nodes that are disconnected from the rest of the network.\n",
    "supporting": [],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}