{
  "hash": "026fdbbc031c0a5021be31a0f8d3194f",
  "result": {
    "markdown": "---\ntitle: \"Week 3 Challenge\"\nauthor: \"Ben Ramsey\"\ndescription: \"Degree and Density of a Network\"\ndate: \"03/06/2023\"\nformat:\n  html:\n    toc: true\n    code-fold: true\n    code-copy: true\n    code-tools: true\n# editor: visual\ncategories: \n  - challenge_3\n  # - railroads\n  # - faostat\n  # - wildbirds\n---\n\n\n\n\n## Challenge Overview\n\nDescribe the many measures of degree, as well as density, of a network and compare \n\n## Degree\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclimate <- read.csv(\"_data/climate0205-allop.csv\", sep =  \";\") %>% subset(select = -c(X))\nclimate.ig <- graph_from_adjacency_matrix(as.matrix(climate), weighted = TRUE, mode = \"directed\", add.rownames = TRUE)\nclimate.net <- as.network(as.matrix(climate), directed = TRUE, weighted = TRUE)\nggnet2(climate.net, label = colnames(climate))\n```\n\n::: {.cell-output-display}\n![](Week3Challenge_BenRamsey_files/figure-html/unnamed-chunk-3-1.png){width=672}\n:::\n:::\n\n\nIf you have not done it before, evaluate the structure of the network (number of edges and vertices, dyad and triad census, etc.).\n\n\n::: {.cell}\n\n```{.r .cell-code}\nprint(climate.net)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n Network attributes:\n  vertices = 34 \n  directed = TRUE \n  hyper = FALSE \n  loops = FALSE \n  multiple = FALSE \n  bipartite = FALSE \n  total edges= 291 \n    missing edges= 0 \n    non-missing edges= 291 \n\n Vertex attribute names: \n    vertex.names \n\nNo edge attributes\n```\n:::\n\n```{.r .cell-code}\ndyad.census(climate.net)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     Mut Asym Null\n[1,]  65  161  335\n```\n:::\n\n```{.r .cell-code}\ntriad.census(climate.net, mode = \"graph\")\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n        0    1   2   3\n[1,] 3023 2016 787 158\n```\n:::\n:::\n\nThis is the Swiss climate policy network, which has 34 vertices and 291 edges. 65 dyads are mutual and 161 are asymmetric. There are 158 triads with 3 edges, and 787 triads with 2 edges. \n\nCompute the many measures of _degree_ of the network of your choice, most preferably directed. Create a data frame called `nodes` where each row corresponds to a node and each column to an attribute of the node, namely the id, name or label, and different measures of degree: total, out-degree, and in-degree. What is the average degree of the network?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nclimate.nodes = data.frame(name = climate.net %v% \"vertex.names\", degree = degree(climate.net), indegree = degree(climate.net, cmode = \"indegree\"), outdegree = degree(climate.net, cmode = \"outdegree\"))\n\nmean(climate.nodes$degree)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 17.11765\n```\n:::\n:::\n\nThe average degree is 17.12. \n\nCompute the distributions of those measures (or histograms if your network is small). What does this tell us about the structure of the network?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nhist(climate.nodes$degree)\n```\n\n::: {.cell-output-display}\n![](Week3Challenge_BenRamsey_files/figure-html/unnamed-chunk-9-1.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(climate.nodes$indegree)\n```\n\n::: {.cell-output-display}\n![](Week3Challenge_BenRamsey_files/figure-html/unnamed-chunk-9-2.png){width=672}\n:::\n\n```{.r .cell-code}\nhist(climate.nodes$outdegree)\n```\n\n::: {.cell-output-display}\n![](Week3Challenge_BenRamsey_files/figure-html/unnamed-chunk-9-3.png){width=672}\n:::\n\n```{.r .cell-code}\nsummary(climate.nodes)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n     name               degree         indegree        outdegree     \n Length:34          Min.   : 2.00   Min.   : 0.000   Min.   : 0.000  \n Class :character   1st Qu.:10.00   1st Qu.: 5.250   1st Qu.: 3.000  \n Mode  :character   Median :16.50   Median : 7.500   Median : 8.000  \n                    Mean   :17.12   Mean   : 8.559   Mean   : 8.559  \n                    3rd Qu.:21.00   3rd Qu.:11.000   3rd Qu.:11.000  \n                    Max.   :40.00   Max.   :22.000   Max.   :29.000  \n```\n:::\n:::\n\nMost of the vertices in the network have a low degree. \n\n## Density\n\nCompute the density of the network. Is this a global or local measure? Does it have a relationship with average degree?\n\n\n::: {.cell}\n\n```{.r .cell-code}\nnetwork.density(climate.net)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.2593583\n```\n:::\n:::\n\nThe density is .259, is a global measure and it does have a relationship with average degree, because it is a measure of the existing edges out of all the possible edges. \n\n## Random Network\n\nCreate a random (Erdos-Renyi) network with the same number of nodes and edges than the network of your choice. On `igraph`, the necessary commands are `random.graph.game(n, p.or.m, type = c(\"gnp\", \"gnm\"), directed = FALSE, loops = FALSE)` (deprecated), `sample_gnp(n, p, directed = FALSE, loops = FALSE)` or `sample_gnm(n, m, directed = FALSE, loops = FALSE)`. The `p.or.m` argument is to specify the probability of an edge $p$ or the number of edges $m$.\n  \nCompare the densities, dyad and triad censuses, and degree distributions, with the measures of the network of your choice. Does the comparison us something about the network of your choice? \n\n\n\n::: {.cell}\n\n```{.r .cell-code}\nset.seed(1)\nrandom.ig <- sample_gnm(34, 291)\ndyad_census(random.ig)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in dyad_census(random.ig): At motifs.c:857 :Dyad census called on\nundirected graph\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n$mut\n[1] 291\n\n$asym\n[1] 0\n\n$null\n[1] 270\n```\n:::\n\n```{.r .cell-code}\ntriad_census(random.ig)\n```\n\n::: {.cell-output .cell-output-stderr}\n```\nWarning in triad_census(random.ig): At motifs.c:1055 :Triad census called on an\nundirected graph\n```\n:::\n\n::: {.cell-output .cell-output-stdout}\n```\n [1]  686    0 2124    0    0    0    0    0    0    0 2334    0    0    0    0\n[16]  840\n```\n:::\n\n```{.r .cell-code}\nedge_density(random.ig)\n```\n\n::: {.cell-output .cell-output-stdout}\n```\n[1] 0.5187166\n```\n:::\n\n```{.r .cell-code}\nrandom.nodes <- data.frame(degree = igraph::degree(random.ig))\nhist(random.nodes$degree)\n```\n\n::: {.cell-output-display}\n![](Week3Challenge_BenRamsey_files/figure-html/unnamed-chunk-13-1.png){width=672}\n:::\n:::\n\nThe Swiss climate policy network has a long right tail when it comes to total degree and it is less dense compared to the randomly generated graph.  \n",
    "supporting": [
      "Week3Challenge_BenRamsey_files"
    ],
    "filters": [
      "rmarkdown/pagebreak.lua"
    ],
    "includes": {},
    "engineDependencies": {},
    "preserve": {},
    "postProcess": true
  }
}